---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-links
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: applicationsets
  source:
    repoURL: https://github.com/ssbagwe/gitops-lab
    targetRevision: main
    path: argocd-apps/repo-links
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
